### PR TITLE
Update to PMS version 1.13.9.5456

### PR DESCRIPTION
**Pull request by TBK**

### CODE REVIEW

**Comment by frebib** [comment]
Damn, we missed this. Will get it merged ASAP, ty

**Comment by frebib** [comment]
Ok this highlighted that our CI fails for PRs. I'm looking into it now, thanks for pointing it out :)

**Comment by TBK** [comment]
No problem. Glad I could help :)

The CI fail seems relative simple. When running the "notify phase" (not sure what terminology Drone uses):
```
  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
secrets: [ webhook_url, notify_token ]
```

the `webhook_url` variable is not available.

**Comment by frebib** [comment]
By default those secrets are only available for the `push`, `tag` and `deployment` events. I've made them available to PRs too so as well as the CI passing, we get the notifications of a PR which is nice!

**Comment by TBK** [comment]
Ah that explains it. Do you host Drone youself or use the EE version?

**Comment by frebib** [comment]
I wasn't aware there was a hosted version. We host it and all of the spritsail infrastructure ourselves

**Comment by TBK** [comment]
k, I have been looking into self-hosted VCS -CI/CD options.

A Gitea + Drone combo seems appealing oppose to the GitLab "walled feature garden".

**Comment by frebib** [comment]
Yeah definitely a good option. Both gitea and Gogs look nice and simple and perfect for a self-hosted ecosystem. It is something we have discussed and will probably put into action at some point, just mirroring to GitHub instead of primarily relying on it.

**Comment by TBK** [comment]
My thought exactly. Thanks for the sparring :P Have a pleasant evening.

**Pull request merged**
